version: '3'

services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRESQL_DATSBASE: sazerac_social
      POSTGRESQL_USER: appuser
      POSTGRESQL_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8081"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: sazerac_social
      DB_PASSWORD: sazerac_social_db
      DB_HOST: db
