default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  template: template0
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: sazerac_social_test
  template: template0
  username: sazerac_social

production:
  <<: *default
  database: sazerac_social_production
  username: sazerac_social
  password: <%= ENV['SAZERAC_SOCIAL_DATABASE_PASSWORD'] %>
